import Head from 'next/head'
import { Fira_Sans } from 'next/font/google'
import { useRouter } from 'next/router'

const firaSans = Fira_Sans({
    subsets: ['latin'],
    weight: '400',
})

export default function NewsDetailPage() {
    const router = useRouter()

    console.log(router.query.newsId)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={firaSans.className}>
                <h1>Notícia | Desenvolvimento</h1>
            </main>
        </>
    )
}
